backend:
  name: github
  repo: dhammafarer/middleman
  branch: master

publish_mode: editorial_workflow

media_folder: "/source/images"

public_folder: "/images"

collections:
  - name: "blog"
    label: "blog"
    folder: "source/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.html"
    fields:
      - {label: "Title", name: "title", widget: "string", default: "title"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "settings"
    label: "Settings"
    editor:
      preview: false
    files:
      - name: "authors"
        label: "Authors"
        file: "data/authors.yml"
        description: "Author descriptions"
        fields:
          - name: authors
            label: Authors
            widget: list
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Description", name: "description", widget: "markdown"}
